### ISSUE TITLE
Bad visibility on hamburger menu options

### ISSUE THREAD

**Issue by DannyTalent** [theweavrs/BreadPlayer#21]
Both PC (when the player window is small) and mobile, the transparent hamburger menu makes it so that it's hard to read the options
![image](https://cloud.githubusercontent.com/assets/23058301/19778073/b944dd8c-9c40-11e6-83d4-9a5bbea1d7e9.png)

It's even more noticeable on mobile, however
![wp_ss_20161027_0002](https://cloud.githubusercontent.com/assets/23058301/19778597/21853b4c-9c43-11e6-9006-96b246e2e25f.png)

**Comment by theweavrs** [comment]
@DannyTalent I made the whole menu a solid color instead of transparent for precisely this reason. What's do you say? What color or combination would be better suited?

**Comment by DannyTalent** [comment]
The current color looks fine, just not transparent. Maybeeee blur would make it look better. Accent color would probably work fine, too, and/or a really dark grey, kinda like what the old Settings app for W10 had (R: 23 G: 23 B: 23) with white text.

PS: I noticed some files from source code are in spanish, would you prefer me to talk in spanish? Cuz I speak spanish too lol

**Comment by theweavrs** [comment]
No, no. English is absolutely fine 😄 

The blur would have a very adverse effect on performance. Maybe I will try solid white-grey color or we can simply use accent color. Later on, we can make a setting for this.

**Comment by DannyTalent** [comment]
Alright

Really? I mean myTube uses it (beta) on mobile, and it isn't really that slow... And the blur changes with the video, so I imagine there's quite a lot of processing happening..
Yeah, dark/light mode setting would be very nice

**Comment by theweavrs** [comment]
Even so, this is a rather a risky thing and nothing we can't do without. I think we should reduce the transparency to a minimum and use the same setting.

**Comment by DannyTalent** [comment]
Right. What about moving the whole screen to the right? As in, not making the menu, instead of coming from the left and overlapping on top of the screen. I think the ESL app does this

**Comment by theweavrs** [comment]
You mean just overlapping the whole of the screen with the menu in the middle?

**Comment by DannyTalent** [comment]
Well, that could work, too, I was thinking of moving the normally visible controls to the right, kinda like the old wp8.1 pivots... But yeah what you said sounds like a good idea. And probably easier to code!

**Comment by theweavrs** [comment]
The search bar will have to be moved to somewhere more convenient. Besides that, all is well.

**Comment by theweavrs** [comment]
![inline](https://cloud.githubusercontent.com/assets/7473959/19781666/bb271eae-9ca3-11e6-84aa-1f1b15af1346.PNG)

Did you mean this?

**Comment by DannyTalent** [comment]
Exactly that, yeah


Ot: Hey if I made a small svg mock up of the app and suggested a few things (design wise) would you consider it? I really wanna help with the development of this app, it's pretty fun

**Comment by theweavrs** [comment]
Of course, I would love that! Actually I would really appreciate that.

**Comment by DannyTalent** [comment]
Alrighty, cuz I feel that some transparent dark screens would make it look a bit better but I'm not so sure, unless I see it. In a few days I'll send you one if I have something decent!

**Comment by theweavrs** [comment]
Perfect!

**Comment by theweavrs** [comment]
@DannyTalent I was thinking of moving the player bar to the bottom like in Groove. What do you say?

**Comment by DannyTalent** [comment]
I think the current layout on mobile is perfect, maybe you can put it on PC as well!

**Comment by DannyTalent** [comment]
Although it might be bad for ux... What about making it stay on top but have the buttons (next, pause, prev, shuffle, etc.) be on top of the progress bar so that there's some extra space on top

**Comment by theweavrs** [comment]
I changed the mobile layout a bit, but basically its the same. I cannot transfer it to PC because I don't think it will look good on bigger screens.

What will we do with the extra space? Not a bad idea, btw.

**Comment by theweavrs** [comment]
The problem with action center occurs on mobiles because of the notification bar. 

I hid the whole play bar to free up all the space I could, I think its more...user-friendly that way. For two reasons: first that a user is not playing with the play bar all the time, so when he does want it he can press the button and voila!

The second reason is the hamburger menu button. It looks awful when placed right below the play bar destroying the whole beauty of the thing.

**Comment by theweavrs** [comment]
As to PCs, the second reason applies + the rectangle where currently playing song info is now showed. Placing the whole thing at the bottom will on one side make it more appropriate and on the other side we will have to get rid of the status bar. I have seen status bar right below the play bar and it looks weird.

**Comment by DannyTalent** [comment]
Ohhh I see... It _might_ be a little hard to discover for an average user though if it's hidden. (Never underestimate end users!) Maybe a little animation later in development might help with that tho.

Which status bar? The one that says Nothing baking? What if you have it appear and disappear, kinda like a small, thin toast notification? Only when it's needed of course, or maybe with an X button to close it...

**Comment by theweavrs** [comment]
How about if its visible on first use with the button to hide? That way the user will know that there _is_ a playbar :)

**Comment by theweavrs** [comment]
@DannyTalent I have released a new alpha update, [go check it out!](https://github.com/theweavrs/BreadPlayer/releases/tag/v0.1.3-alpha)

**Comment by theweavrs** [comment]
![inline](https://cloud.githubusercontent.com/assets/7473959/19807490/c1528386-9d39-11e6-9c3a-ec7b2b3320b0.PNG)

Do tell how it looks? Better or worse?

**Comment by DannyTalent** [comment]
Yes! Loving that placement! I did get the new alpha for my phone, ty! You might wanna reopen the double song issue tho :/ it's still happening...

**Comment by theweavrs** [comment]
Strange, it wasn't appearing in the emulator at all.

**Comment by DannyTalent** [comment]
Yep... I'll record a video tonight to show you exactly what's happening.. Can't earlier because of classes :/

**Comment by theweavrs** [comment]
Yes! That would certainly help a lot.

**Comment by DannyTalent** [comment]
![wp_ss_20161101_0001](https://cloud.githubusercontent.com/assets/23058301/19907350/76282616-a04c-11e6-9279-fb8c8e41f7d4.png)
Controls don't show up when you just opened up the app. Even if you start playing a song. Closing and opening the tab fixes it, however

**Comment by theweavrs** [comment]
yes, I missed those figures out. Fixing it now.

**Comment by MightyK1337** [comment]
While using the dark theme, the letters for jump lists and the jump list is not visible.

**Comment by theweavrs** [comment]
@MightyK1337  I will try and reproduce this.

**Comment by theweavrs** [comment]
@MightyK1337 Is it visible in Light Theme?

**Comment by theweavrs** [comment]
@MightyK1337 Reproduced and fixed. There was also a crash while jumping to a specific letter.

**Comment by DannyTalent** [comment]
http://imgur.com/a/CPj5y (can't upload here, on mobile) it's from bottom to top, the 1st one shows landscape mode, a little awkward with the song info and the hamburger menu... Then, when u go back to portrait, the hamburger button from the playlist, which usually is transparent (as in the top pic), goes red (accent color).

**Comment by theweavrs** [comment]
Yes. This is certainly a bug in the UI adaptation to different screens. Fixing right away!

**Comment by MightyK1337** [comment]
Alphabets for jump lists not visible.

**Comment by theweavrs** [comment]
@MightyK1337 In dark theme or light?

**Comment by MightyK1337** [comment]
It is the dark theme. 
Also - don't know if this is a issue- when the first time i play something and navigate from the app, song stops playing. I need to go back to app and then navigate to others for it to work in background.

**Comment by theweavrs** [comment]
I will surely investigate this further.

**Comment by theweavrs** [comment]
@MightyK1337 Can you explain the exact steps to reproduce this new issue?

**Comment by MightyK1337** [comment]
Sorry for the late reply.
1. Play a song
2. navigate away from the app like pressing the home key
3. the song stops playing
4. navigate back to the app, by pressing the back key or from task switcher
5. song starts playing again.
6. now navigate away from the app again.
7. the song will continue to play in background

Expected behavior: song should continue to play in the background,even when navigating from the app for the first time.

**Comment by MightyK1337** [comment]
![wp_ss_20161203_0001_ink_li](https://cloud.githubusercontent.com/assets/15900598/20856419/3e44427e-b934-11e6-8dd8-9fcd40cdcd0d.jpg)

Remove the now playing bar highlighted, when nothing is being played. We can look at more number of songs, if it is removed. also improves usability

**Comment by MightyK1337** [comment]
![wp_ss_20161203_0002_ink_li](https://cloud.githubusercontent.com/assets/15900598/20856433/99323e20-b934-11e6-84bf-233343219102.jpg)
This arrow appears after using the jumplist. pressing it does not work and after this appears, the jump list also stops working.
